### ISSUE TITLE
General.json

### ISSUE THREAD

**Issue by daedalas1981** [DustinWatts/FreeTouchDeck#54]
If you use the Upload Menu Config to upload general.json, you get an error that you can't upload it.

**Comment by DustinWatts** [comment]
Ah, I see! This is because checks if the filename that is uploaded is one that is used in the config. Since 0.9.11 the config filesnames have changed a bit but I forgot to change the allowed filenames in `Webserver.h`. The same would happen if you try to upload wificonfig.json. Quick fix:

`line 223 Webserver.h` should be:
```
if (filename != "menu1.json" && filename != "menu2.json" && filename != "menu3.json" && filename != "menu4.json" && filename != "menu5.json" && filename != "homescreen.json" && filename != "general.json", && filename != "wificonfig.json")
 ```

**Comment by daedalas1981** [comment]
Awesome, thanks! Updated code, will try later!

**Comment by DustinWatts** [comment]
https://github.com/DustinWatts/FreeTouchDeck/commit/faa9d31d738b3f14bbc285f9732b96536a5d19ab Fixes this.
