### ISSUE TITLE
Different version in master, compared to that on the hardware

### ISSUE THREAD

**Issue by danielhunt** [DustinWatts/FreeTouchDeck#56]
Version `0.9.11` is in `master` at the moment, but version `0.9.12` shipped on the devices in batch 2 of the Tindie run.
Was there much changed between those versions? (It might be worth using Github tags to keep track of the versions as you create them)

@DustinWatts can you push the `0.9.12` code to github so we can see if anything important needs to be included in things like #51 or #52 please?

**Comment by DustinWatts** [comment]
Hi @danielhunt Nothing has changed since 0.9.11, when I made the binary that I used to flash the ESP32 TouchDown, I accidentally set the version number to 0.9.12 but that should be version 0.9.11. 

The only thing different is that `USECAPTOUCH` and `speakerPin` are defined.

Hope this explains the difference in version numbers. Feel free to reopen if not.
